"use strict";
exports.__esModule = true;
var carro_1 = require("./carro");
var c1;
var nome;
c1 = new carro_1.Carro();
c1.setAno(1996);
c1.setModelo("Gol g2");
c1.setCor("Roxo");
c1.setPlaca("SCB-1992");
c1.ligar();
c1.ligar();
c1.desligar();
